name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate the snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: purpocto
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
